spring:
  application:
    name: springsecurity-study
  # datasource
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/community_management_system?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
# mybatis-plus
mybatis-plus:
  type-aliases-package: com.lxy.springsecuritystudy.model.entity
  mapper-locations: classpath:mapper/*.xml

