spring:
  application:
    name: integrating-mybatis
  # 数据源配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mybatisdb?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
#mybatis配置
mybatis:
  type-aliases-package: com.lxy.integratingmybatis.model.entity
  mapper-locations: classpath:mapper/*.xml